name: flutter_note
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.23.0+1
  flutter_svg_provider: ^0.1.11
  font_awesome_flutter: ^9.2.0
  path: ^1.8.0
  provider: ^6.0.1
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/backgrounds/
    - assets/logo.png

